import {ArrowRight,BadgeCheck,Coffee,Download,FileText,Send} from 'lucide-react';
import {Link,useParams} from 'react-router-dom';
import {coffees} from '../data/content';
import {Beans,CoffeeCard,PageCta,PageHero,Title} from '../components/Common';
import {NotFoundPage} from './UtilityPages';

export function CoffeesPage(){return <main><PageHero eyebrow="Our coffee" title="Ethiopian coffees with a clearer buyer story." text="A polished sample catalogue prepared for Koffera’s future verified origins, grades, crop years and availability." actions={<><Link className="btn cream" to="/origins">Explore origins <ArrowRight size={17}/></Link><Link className="btn outline" to="/request-offer">Request current offer</Link></>}/><section className="section creamsec"><div className="wrap"><div className="catalogue"><span><Coffee size={17}/> Sample catalogue — final product data is required.</span><div><button>Origin</button><button>Process</button><button>Availability</button></div></div><div className="cards cataloguecards">{coffees.map(c=><CoffeeCard key={c.name} coffee={c}/>)}</div></div></section><PageCta title="Need a current coffee offer?" text="Send your preferred origin, grade, process, quantity and destination."/></main>}

export function CoffeeDetailPage(){const{slug}=useParams();const coffee=coffees.find(x=>x.slug===slug);if(!coffee)return <NotFoundPage/>;const specs=[['Region',coffee.region],['Process',coffee.process],['Grade',coffee.grade],['Crop year',coffee.cropYear],['Altitude',coffee.altitude],['Variety',coffee.variety],['Availability',coffee.availability],['Packaging','To confirm']];return <main><section className="producthero"><div className="wrap productgrid"><div><span className="eyelight">Sample coffee record</span><h1>{coffee.name}</h1><p>{coffee.text}</p><div className="actions"><Link className="btn cream" to="/request-offer">Request this coffee <ArrowRight size={17}/></Link><Link className="btn outline" to="/coffees">Back to catalogue</Link></div></div><div className={`productvisual ${coffee.tone}`}><Beans/><span>{coffee.process}</span><strong>{coffee.region}</strong><small>Final product image required</small></div></div></section><section className="section"><div className="wrap detail-layout"><div><Title eyebrow="Product overview" title="Structured for professional coffee evaluation." text="All technical fields remain clearly marked until Koffera supplies verified product specifications."/><div className="specgrid">{specs.map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div></div><aside className="samplebox"><BadgeCheck/><h3>Sample cup profile</h3><p>{coffee.cup}</p><hr/><span>Moisture</span><b>To confirm</b><span>Screen size</span><b>To confirm</b><span>Certification</span><b>To confirm</b></aside></div></section><section className="section creamsec"><div className="wrap two-panels"><article><FileText/><span>Specification sheet</span><h2>Technical PDF placeholder</h2><p>Add the approved product specification document when available.</p><button className="btn mutedbtn" disabled><Download size={16}/> Download coming soon</button></article><article><Send/><span>Buyer action</span><h2>Request samples or an offer</h2><p>Use the dedicated enquiry form to provide quantity and destination information.</p><Link className="btn dark" to="/request-offer">Open request form <ArrowRight size={16}/></Link></article></div></section><PageCta title={`Interested in ${coffee.name}?`} text="Tell Koffera your required grade, quantity, packaging and destination."/></main>}
