import {ArrowRight,BadgeCheck,Coffee,Download,FileText,Send} from '../components/Icons';
import {Link,useParams} from 'react-router-dom';
import {coffees} from '../data/content';
import {Beans,CoffeeCard,PageCta,PageHero,Title} from '../components/Common';
import {NotFoundPage} from './UtilityPages';

export function CoffeesPage(){return <main><PageHero eyebrow="Our coffee" title="Ethiopian coffees with a clearer buyer story." text="These are illustrative catalogue records prepared to show how Koffera can present verified origins, grades, crop years, cup profiles and availability." actions={<><Link className="btn cream" to="/origins">Explore origins <ArrowRight size={17}/></Link><Link className="btn outline" to="/request-offer">Request current offer</Link></>}/><section className="section creamsec"><div className="wrap"><div className="catalogue"><span><Coffee size={17}/> Demonstration catalogue — request the current approved offer list.</span><div><button disabled>Origin</button><button disabled>Process</button><button disabled>Availability</button></div></div><div className="cards cataloguecards">{coffees.map(c=><CoffeeCard key={c.name} coffee={c}/>)}</div></div></section><PageCta title="Need a current coffee offer?" text="Send your preferred origin, grade, process, quantity and destination."/></main>}

export function CoffeeDetailPage(){const{slug}=useParams();const coffee=coffees.find(x=>x.slug===slug);if(!coffee)return <NotFoundPage/>;const specs=[['Region',coffee.region],['Process',coffee.process],['Grade',coffee.grade],['Crop year',coffee.cropYear],['Altitude',coffee.altitude],['Variety',coffee.variety],['Availability',coffee.availability],['Packaging',coffee.packaging]];return <main><section className="producthero"><div className="wrap productgrid"><div><span className="eyelight">Illustrative coffee record</span><h1>{coffee.name}</h1><p>{coffee.text}</p><div className="actions"><Link className="btn cream" to="/request-offer">Request this coffee <ArrowRight size={17}/></Link><Link className="btn outline" to="/coffees">Back to catalogue</Link></div></div><div className={`productvisual ${coffee.tone}`}><Beans/><span>{coffee.process}</span><strong>{coffee.region}</strong><small>Final product image required</small></div></div></section><section className="section"><div className="wrap detail-layout"><div><Title eyebrow="Product overview" title="Structured for professional coffee evaluation." text="The values below are demonstration content, not a confirmed Koffera offer. Replace them with the approved lot specification before launch."/><div className="specgrid">{specs.map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div></div><aside className="samplebox"><BadgeCheck/><h3>Illustrative cup profile</h3><p>{coffee.cup}</p><hr/><span>Moisture</span><b>{coffee.moisture}</b><span>Screen size</span><b>{coffee.screen}</b><span>Certification</span><b>{coffee.certification}</b></aside></div></section><section className="section creamsec"><div className="wrap two-panels"><article><FileText/><span>Specification sheet</span><h2>Technical PDF area</h2><p>The final download should contain the approved physical, cup, packaging and availability information for the selected lot.</p><button className="btn mutedbtn" disabled><Download size={16}/> Download coming soon</button></article><article><Send/><span>Buyer action</span><h2>Request samples or an offer</h2><p>Provide quantity, destination, packaging and expected purchase timing so the export team can respond usefully.</p><Link className="btn dark" to="/request-offer">Open request form <ArrowRight size={16}/></Link></article></div></section><PageCta title={`Interested in ${coffee.name}?`} text="Tell Koffera your required grade, quantity, packaging and destination."/></main>}
