import {ArrowRight,BadgeCheck,CheckCircle2,Mail,MapPin,Phone,Send} from '../components/Icons';
import {Link} from 'react-router-dom';
import {company,origins} from '../data/content';
import {Media,PageHero,Title} from '../components/Common';

export function AboutPage(){return <main><PageHero eyebrow="About Koffera" title="Rooted in Ethiopia. Designed for lasting coffee partnerships." text="A focused company story balancing Ethiopian coffee heritage, leadership and commercial credibility."/><section className="section"><div className="wrap twocol"><Media portrait title="Company or founder image"/><div><Title eyebrow="Our company" title="A concise story with stronger business relevance." text="Koffera is presented as an Ethiopian coffee-export brand serving roasters, importers, distributors and other professional buyers."/><p className="body">The final page should explain how the company sources coffee, evaluates quality, works with suppliers, prepares export documentation and supports buyers. Replace this demo paragraph with approved legal identity, company history, export experience and real photography.</p><Link className="btn dark" to="/contact">Contact Koffera <ArrowRight size={16}/></Link></div></div></section><section className="section creamsec"><div className="wrap mission"><article><span>VISION</span><h2>Represent Ethiopian coffee with integrity in international markets.</h2><p>Demonstration wording that should be approved or replaced by management.</p></article><article><span>MISSION</span><h2>Connect buyers with quality coffee and dependable export support.</h2><p>The final mission should describe actual sourcing, quality and service responsibilities.</p></article></div></section></main>}

export function RequestOfferPage(){return <main><PageHero eyebrow="Request an offer" title="Give Koffera the information needed for a useful coffee offer." text="The form is designed for international buyers. Submission delivery and spam protection still need backend connection."/><section className="section creamsec"><div className="wrap offer-layout"><aside><span className="eye">BEFORE YOU SUBMIT</span><h2>Prepare your purchasing requirements.</h2><p>A complete request reduces unnecessary back-and-forth and helps the export team respond accurately.</p><div className="offer-checks"><p><CheckCircle2/> Preferred origin</p><p><CheckCircle2/> Grade and process</p><p><CheckCircle2/> Required quantity</p><p><CheckCircle2/> Packaging preference</p><p><CheckCircle2/> Destination country or port</p><p><CheckCircle2/> Expected purchase timing</p></div><div className="demo-note"><BadgeCheck/><span><b>Demo form</b> This version does not send data yet.</span></div></aside><OfferForm/></div></section></main>}

function OfferForm(){return <form className="offer-form" onSubmit={e=>e.preventDefault()}><span className="eye">COFFEE REQUIREMENTS</span><h2>Commercial enquiry</h2><div className="formgrid"><label>Full name<input required placeholder="Your name"/></label><label>Company<input required placeholder="Company name"/></label><label>Business email<input required type="email" placeholder="name@company.com"/></label><label>Country<input required placeholder="Country"/></label><label>Buyer type<select defaultValue=""><option value="" disabled>Select buyer type</option><option>Specialty roaster</option><option>Importer / distributor</option><option>Private-label brand</option><option>Café / hospitality</option><option>Retail coffee company</option><option>Other</option></select></label><label>Expected purchase date<input type="month"/></label><label>Preferred origin<select defaultValue=""><option value="">Any available origin</option>{origins.map(([name])=><option key={name}>{name}</option>)}</select></label><label>Processing method<select defaultValue=""><option value="">Any process</option><option>Washed</option><option>Natural</option><option>Other / open to advice</option></select></label><label>Grade requirement<input placeholder="Example: Grade 1"/></label><label>Estimated quantity<input required placeholder="Bags, kg or containers"/></label><label>Packaging preference<input placeholder="Example: 60 kg bags with liner"/></label><label>Destination port<input placeholder="Country or port"/></label><label>Certification requirement<input placeholder="Certification, if required"/></label><label>Sample required<select defaultValue="Yes"><option>Yes</option><option>No</option><option>Not sure</option></select></label><label className="full">Additional message<textarea rows="6" required placeholder="Include cup expectations, timing and any other commercial requirements."/></label><label className="consent full"><input type="checkbox" required/> I agree that Koffera may use this information to respond to my enquiry.</label><button className="btn dark full">Submit request <Send size={16}/></button></div></form>}

export function ContactPage(){return <main><PageHero eyebrow="Contact" title="Contact Koffera or send a general message." text="For coffee pricing, samples and purchasing requirements, use the dedicated Request an Offer page." actions={<Link className="btn cream" to="/request-offer">Request an offer <ArrowRight size={17}/></Link>}/><section className="section creamsec"><div className="wrap contact"><aside><span className="eye">DIRECT CONTACT</span><h2>Let’s start with the right information.</h2><p>Verify these details before final launch.</p><a href={`mailto:${company.email}`}><Mail/><span>Email<b>{company.email}</b></span></a><a href={`tel:${company.phone.split(' ').join('')}`}><Phone/><span>Phone<b>{company.phone}</b></span></a><div><MapPin/><span>Office<b>{company.location}</b></span></div><div className="map">Office map or facility image</div></aside><form onSubmit={e=>e.preventDefault()}><span className="eye">GENERAL MESSAGE</span><h2>Contact form</h2><p>Email delivery can be connected later.</p><div className="formgrid"><label>Full name<input required placeholder="Your name"/></label><label>Company<input placeholder="Company name"/></label><label>Email<input required type="email" placeholder="name@company.com"/></label><label>Country<input placeholder="Country"/></label><label className="full">Subject<input required placeholder="How can Koffera help?"/></label><label className="full">Message<textarea rows="7" required placeholder="Write your message."/></label><button className="btn dark full">Send message <ArrowRight size={16}/></button></div></form></div></section></main>}
