import {ArrowRight,Coffee,FileCheck2,Globe2,Sprout} from '../components/Icons';
import {Link} from 'react-router-dom';
import {company,coffees,marketSegments,serviceCards} from '../data/content';
import {Beans,Brand,CoffeeCard,Media,PageCta,Title} from '../components/Common';

function Bag(){return <div className="bagscene"><div className="rings"/><Beans/><div className="bag"><div className="bagbeans"><Beans/></div><div className="label"><Brand light/><hr/><small>PREMIUM ETHIOPIA</small><b>100% ARABICA COFFEE</b><span>CREATED WITH CARE FOR YOU</span></div><div className="bagbeans bottom"><Beans/></div></div><small className="replace">Replace with final product photo</small></div>}

export default function HomePage(){return <main>
<section className="hero"><div className="wrap herogrid"><div><span className="eyelight">Authentic Ethiopian coffee</span><h1>Ethiopia’s coffee heritage, prepared for the world.</h1><p>Koffera connects international buyers with Ethiopian coffee through a warmer brand identity, clearer product presentation and a professional export enquiry journey.</p><div className="actions"><Link className="btn cream" to="/coffees">Explore our coffee <ArrowRight size={17}/></Link><Link className="btn outline" to="/request-offer">Request an offer</Link></div><div className="facts"><span>✓ Ethiopian Arabica</span><span>✓ B2B export focus</span><span>✓ Buyer enquiry ready</span></div></div><Bag/></div></section>
<section className="proof"><div className="wrap proofgrid">{[[Sprout,'Origin-led','Ethiopian sourcing story'],[Coffee,'Buyer-ready','Coffee presentation'],[FileCheck2,'Professional','Export information'],[Globe2,'International','Partnership focus']].map(([I,a,b])=><div key={a}><I/><span><b>{a}</b>{b}</span></div>)}</div></section>
<section className="section"><div className="wrap intro"><div className="story"><Beans/><span>FROM ETHIOPIA</span><b>Born at origin.<br/>Built for buyers.</b></div><div><Title eyebrow="The Koffera story" title="A warmer, more authentic coffee-export identity." text="The website uses Koffera’s coffee-brown, cream and white brand feeling while giving buyers clear access to products, origins, quality and export information."/><div className="lines"><p><b>01</b><span><strong>Authentic positioning</strong> Ethiopian identity through product and origin.</span></p><p><b>02</b><span><strong>Commercial clarity</strong> Products, services and enquiries are easy to find.</span></p><p><b>03</b><span><strong>Premium restraint</strong> Better spacing, typography and visual rhythm.</span></p></div><Link className="textlink" to="/about">Discover Koffera <ArrowRight size={16}/></Link></div></div></section>
<section className="section creamsec"><div className="wrap"><Title center eyebrow="Our coffee" title="Ethiopian coffees presented with character." text="These illustrative records show how verified Koffera offers can later be presented with real grades, crop years, cup profiles and availability."/><div className="cards">{coffees.slice(0,3).map(c=><CoffeeCard key={c.name} coffee={c}/>)}</div><div className="centerbtn"><Link className="btn dark" to="/coffees">View the catalogue <ArrowRight size={17}/></Link></div></div></section>
<section className="section darksec"><div className="wrap"><Title light eyebrow="Export services" title="A clearer path from discovery to shipment." text="Services are presented around what international buyers need to understand before beginning a transaction."/><div className="services">{serviceCards.map(([I,t,d],i)=><article key={t}><div><span>0{i+1}</span><I/></div><h3>{t}</h3><p>{d}</p></article>)}</div><div className="dark-action"><Link className="btn cream" to="/export-services">Explore export services <ArrowRight size={17}/></Link></div></div></section>
<section className="section founder"><div className="wrap twocol"><Media portrait title="Founder portrait"/><div><Title eyebrow="Founder & company" title="Leadership supports the coffee story—not the other way around." text="The founder remains visible as part of Koffera’s credibility, while products, sourcing and buyer needs remain central."/><blockquote>“The final message will focus on Ethiopian coffee quality, trusted relationships and dependable export execution.”</blockquote><p><b>{company.founder}</b><br/><small>Founder — final biography required</small></p><Link className="textlink" to="/about">Read the company story <ArrowRight size={16}/></Link></div></div></section>
<section className="section"><div className="wrap"><Title center eyebrow="Who we serve" title="Built for serious coffee buyers."/><div className="markets">{marketSegments.slice(0,4).map(([I,x],i)=><article key={x}><span>0{i+1}</span><I/><h3>{x}</h3><p>Professional product information and a clear enquiry path.</p><Link to="/markets" aria-label={`Learn about ${x}`}><ArrowRight size={16}/></Link></article>)}</div></div></section>
<section className="section videosec"><div className="wrap"><Media/></div></section><PageCta/>
</main>}
