import {ArrowRight,Play} from 'lucide-react';
import {Link} from 'react-router-dom';

export function Brand({light=false}){return <Link className={`brand ${light?'light':''}`} to="/"><b>K<span>O</span>FFERA</b><small>COFFEE EXPORT</small></Link>}
export function Title({eyebrow,title,text,light=false,center=false}){return <div className={`title ${light?'light':''} ${center?'center':''}`}><span>{eyebrow}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
export function Beans(){return <div className="beans" aria-hidden="true">{Array.from({length:12},(_,i)=><i key={i}/>)}</div>}
export function Media({title='Koffera Coffee Story',portrait=false}){return <div className={`media ${portrait?'portrait':''}`}><Beans/><button aria-label={`Play ${title}`}><Play fill="currentColor"/></button><b>{title}</b><small>Reserved for your final image or video.</small></div>}
export function PageHero({eyebrow,title,text,actions}){return <section className="pagehero"><Beans/><div className="wrap"><span className="eyelight">{eyebrow}</span><h1>{title}</h1><p>{text}</p>{actions&&<div className="actions">{actions}</div>}</div></section>}
export function PageCta({title='Ready to discuss Ethiopian coffee?',text='Share your preferred origin, process, grade, quantity and destination.',button='Request an offer',to='/request-offer'}){return <section className="cta"><div className="wrap"><div><span className="eyelight">Buyer enquiry</span><h2>{title}</h2><p>{text}</p></div><Link className="btn cream" to={to}>{button} <ArrowRight size={17}/></Link></div></section>}
export function CoffeeCard({coffee}){return <article className="card"><div className={`visual ${coffee.tone}`}><Beans/><span>{coffee.process}</span></div><div className="cardbody"><div className="meta"><span>{coffee.region}</span><span>{coffee.grade}</span></div><h3>{coffee.name}</h3><p>{coffee.text}</p><div className="cardfoot"><span>Availability to confirm</span><Link aria-label={`View ${coffee.name}`} to={`/coffees/${coffee.slug}`}><ArrowRight size={17}/></Link></div></div></article>}
