import {useEffect,useState} from 'react';
import {ArrowRight,ChevronDown,Coffee,Globe2,MapPin,Menu,ShieldCheck,Ship,X} from 'lucide-react';
import {Link,NavLink,useLocation} from 'react-router-dom';
import {company} from '../data/content';
import {Brand} from './Common';

export function Scroll(){const{pathname}=useLocation();useEffect(()=>window.scrollTo(0,0),[pathname]);return null}

export function Header(){
const[open,setOpen]=useState(false);const[expanded,setExpanded]=useState('');const{pathname}=useLocation();
const close=()=>{setOpen(false);setExpanded('')};
const coffeeActive=pathname.startsWith('/coffee')||pathname.startsWith('/origin')||pathname.startsWith('/quality');
const serviceActive=pathname.startsWith('/export-services')||pathname.startsWith('/markets');
return <><div className="top"><div className="wrap">Premium Ethiopian coffee for international buyers <em><MapPin size={13}/> Addis Ababa, Ethiopia</em></div></div><header><div className="wrap nav"><Brand/><nav className={open?'open':''}><NavLink to="/" onClick={close}>Home</NavLink><div className={`navgroup ${expanded==='coffee'?'expanded':''}`}><button className={coffeeActive?'current':''} onClick={()=>setExpanded(expanded==='coffee'?'':'coffee')}>Coffee <ChevronDown size={15}/></button><div className="dropdown"><Link to="/coffees" onClick={close}><Coffee size={16}/><span><b>Coffee Catalogue</b><small>Explore current sample offers</small></span></Link><Link to="/origins" onClick={close}><MapPin size={16}/><span><b>Coffee Origins</b><small>Discover Ethiopian regions</small></span></Link><Link to="/quality-traceability" onClick={close}><ShieldCheck size={16}/><span><b>Quality & Traceability</b><small>See the proposed quality flow</small></span></Link></div></div><div className={`navgroup ${expanded==='services'?'expanded':''}`}><button className={serviceActive?'current':''} onClick={()=>setExpanded(expanded==='services'?'':'services')}>Services <ChevronDown size={15}/></button><div className="dropdown"><Link to="/export-services" onClick={close}><Ship size={16}/><span><b>Export Services</b><small>From enquiry to shipment</small></span></Link><Link to="/markets" onClick={close}><Globe2 size={16}/><span><b>Target Markets</b><small>Buyer groups Koffera serves</small></span></Link></div></div><NavLink to="/about" onClick={close}>About</NavLink><NavLink to="/contact" onClick={close}>Contact</NavLink><Link className="btn small" to="/request-offer" onClick={close}>Request an offer <ArrowRight size={15}/></Link></nav><button className="menu" aria-label="Toggle navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header></>}

export function Footer(){return <footer><div className="wrap foot"><div><Brand light/><p>Warm, premium Ethiopian coffee presentation for serious international buyers.</p></div><div><h4>COFFEE</h4><Link to="/coffees">Catalogue</Link><Link to="/origins">Origins</Link><Link to="/quality-traceability">Quality & Traceability</Link></div><div><h4>SERVICES</h4><Link to="/export-services">Export Services</Link><Link to="/markets">Target Markets</Link><Link to="/request-offer">Request an Offer</Link></div><div><h4>CONTACT</h4><a href={`mailto:${company.email}`}>{company.email}</a><a href={`tel:${company.phone.split(' ').join('')}`}>{company.phone}</a><span>{company.location}</span></div><div><h4>INFORMATION</h4><Link to="/about">About</Link><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link></div></div><div className="wrap copy">© {new Date().getFullYear()} Koffera Coffee <span>Prototype content requires final approval.</span></div></footer>}
