import {useEffect,useState} from'react';
import{ArrowRight,Coffee,FileCheck2,Globe2,Mail,MapPin,Menu,PackageCheck,Phone,Play,ShieldCheck,Sprout,X}from'lucide-react';
import{Link,NavLink,Route,Routes,useLocation}from'react-router-dom';
const company={phone:'+251 920 318 757',email:'firaolkebede777@gmail.com',location:'Addis Ababa, Ethiopia',founder:'Firaol Kebede'};
const coffees=[
{name:'Yirgacheffe Washed',region:'Yirgacheffe',process:'Washed',tone:'gold',text:'Floral, citrus and tea-like sample profile. Final grade, crop year and lot details are required.'},
{name:'Guji Natural',region:'Guji',process:'Natural',tone:'red',text:'Fruit-led natural sample profile prepared for final cup score, altitude and availability.'},
{name:'Sidama Washed',region:'Sidama',process:'Washed',tone:'olive',text:'Balanced washed-coffee sample with space for verified specification and export information.'}
];
const services=[
[Coffee,'Coffee sourcing','Present verified Ethiopian origins, processes and grades in a buyer-friendly catalogue.'],
[ShieldCheck,'Quality coordination','Explain sampling, cupping and pre-shipment checks using the company’s actual process.'],
[FileCheck2,'Export documentation','Show buyers what commercial and shipment documentation Koffera can provide.'],
[PackageCheck,'Shipment support','Guide buyers from the first offer through packaging, loading and shipment communication.']
];
function ScrollTop(){const{pathname}=useLocation();useEffect(()=>window.scrollTo(0,0),[pathname]);return null}
function Brand({inverse=false}){return <Link className={`brand ${inverse?'inverse':''}`} to="/"><span>K<span className="bean-o">O</span>FFERA</span><small>Coffee Export</small></Link>}
function Header(){const[open,setOpen]=useState(false);return <><div className="topbar"><div className="container">Premium Ethiopian coffee for international buyers <span><MapPin size={13}/> Addis Ababa, Ethiopia</span></div></div><header><div className="container nav"><Brand/><nav className={open?'open':''}>{[['Home','/'],['Our Coffee','/coffees'],['About','/about'],['Contact','/contact']].map(([label,to])=><NavLink key={to} to={to} onClick={()=>setOpen(false)}>{label}</NavLink>)}<Link className="btn small" to="/contact" onClick={()=>setOpen(false)}>Start a partnership <ArrowRight size={15}/></Link></nav><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header></>}
function Footer(){return <footer><div className="container footer-grid"><div><Brand inverse/><p>Ethiopian coffee presented with warmth, clarity and a professional buyer-enquiry journey.</p></div><div><h4>Explore</h4><Link to="/coffees">Our Coffee</Link><Link to="/about">About Koffera</Link><Link to="/contact">Buyer Enquiry</Link></div><div><h4>Contact</h4><a href={`mailto:${company.email}`}>{company.email}</a><a href={`tel:${company.phone.replace(/\s/g,'')}`}>{company.phone}</a><span>{company.location}</span></div><div><h4>Information</h4><Link to="/privacy">Privacy Policy</Link><Link to="/terms">Terms</Link><span>Social links to be added</span></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Koffera Coffee</span><span>Prototype content requires final approval.</span></div></footer>}
function Heading({eyebrow,title,text,center=false,light=false}){return <div className={`heading ${center?'center':''} ${light?'light':''}`}><span>{eyebrow}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
function Beans({few=false}){return <div className={`beans ${few?'few':''}`} aria-hidden="true">{Array.from({length:few?8:14},(_,i)=><i key={i}/>)}</div>}
function Packshot(){return <div className="pack-wrap"><div className="orbit one"/><div className="orbit two"/><Beans/><div className="pack"><div className="pack-top"><Beans few/></div><div className="pack-label"><Brand inverse/><hr/><small>Premium Ethiopia</small><strong>100% Arabica Coffee</strong><span>Created with care for you</span></div><div className="pack-bottom"><Beans few/></div></div><em>Replace with final product photography</em></div>}
function Media({title,portrait=false}){return <div className={`media ${portrait?'portrait':''}`}><Beans/><button><Play fill="currentColor"/></button><strong>{title}</strong><span>Reserved for your final image or video link.</span></div>}
function CoffeeCard({coffee}){return <article className="coffee-card"><div className={`coffee-image ${coffee.tone}`}><Beans/><span>{coffee.process}</span></div><div className="coffee-body"><div className="meta"><span>{coffee.region}</span><span>Sample grade</span></div><h3>{coffee.name}</h3><p>{coffee.text}</p><div className="card-foot"><span>Availability to confirm</span><Link to="/contact"><ArrowRight size={17}/></Link></div></div></article>}
function Home(){return <main><section className="hero"><div className="container hero-grid"><div><span className="eyebrow light">Authentic Ethiopian coffee</span><h1>Ethiopia’s coffee heritage, prepared for the world.</h1><p>Koffera connects international buyers with Ethiopian coffee through a warmer brand experience, clearer product presentation and a professional export-enquiry journey.</p><div className="actions"><Link className="btn cream" to="/coffees">Explore our coffee <ArrowRight size={17}/></Link><Link className="btn outline" to="/contact">Start your partnership</Link></div><div className="hero-points"><span>✓ Ethiopian Arabica</span><span>✓ B2B export focus</span><span>✓ Buyer enquiry ready</span></div></div><Packshot/></div></section>
<section className="proof"><div className="container proof-grid">{[[Sprout,'Origin-led','Ethiopian sourcing story'],[Coffee,'Buyer-ready','Coffee presentation'],[FileCheck2,'Professional','Export information'],[Globe2,'International','Partnership focus']].map(([Icon,a,b])=><div key={a}><Icon/><span><strong>{a}</strong>{b}</span></div>)}</div></section>
<section className="section"><div className="container intro"><div className="origin-card"><Beans/><span>From Ethiopia</span><strong>Born at origin.<br/>Built for buyers.</strong></div><div><Heading eyebrow="The Koffera story" title="A warmer and more credible coffee-export identity." text="This redesign returns to Koffera’s coffee-brown, cream and white identity while improving hierarchy, desktop presentation and buyer conversion."/><div className="numbered">{[['01','Authentic positioning','Ethiopian identity through origin, product and story.'],['02','Commercial clarity','Products, services and enquiries are easier to understand.'],['03','Premium restraint','Warm colours and cleaner typography replace generic UI.']].map(([n,a,b])=><div key={n}><span>{n}</span><p><strong>{a}</strong> {b}</p></div>)}</div><Link className="text-link" to="/about">Discover Koffera <ArrowRight size={16}/></Link></div></div></section>
<section className="section cream-bg"><div className="container"><Heading center eyebrow="Our coffee" title="Ethiopian coffees presented with character." text="These are polished sample records. Replace them with Koffera’s verified grades, crop years, cup profiles and availability."/><div className="coffee-grid">{coffees.map(c=><CoffeeCard key={c.name} coffee={c}/>)}</div><div className="section-action"><Link className="btn dark" to="/coffees">View the catalogue <ArrowRight size={17}/></Link></div></div></section>
<section className="section espresso"><div className="container"><Heading light eyebrow="Export services" title="A clearer path from coffee discovery to shipment." text="Each service is framed around what an international buyer needs before starting a commercial conversation."/><div className="services">{services.map(([Icon,title,text],i)=><article key={title}><div><span>0{i+1}</span><Icon/></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section className="section founder"><div className="container split"><Media portrait title="Founder portrait"/><div><span className="eyebrow">Founder & company story</span><h2>Leadership should support the coffee story—not replace it.</h2><p>Koffera’s founder remains visible, but products, sourcing and buyer needs now stay at the centre of the homepage.</p><blockquote>“Our final message will focus on Ethiopian coffee quality, trusted relationships and dependable export execution.”</blockquote><strong>{company.founder}</strong><small>Founder — final biography required</small><br/><Link className="text-link" to="/about">Read the company story <ArrowRight size={16}/></Link></div></div></section>
<section className="section"><div className="container"><Heading center eyebrow="Who we serve" title="Built for serious coffee buyers." text="The original target markets are retained with a cleaner commercial hierarchy."/><div className="markets">{['Specialty roasters','Importers & distributors','Private-label brands','Cafés & hospitality'].map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>Clear product, quality and enquiry information for professional coffee purchasing.</p><ArrowRight size={16}/></article>)}</div></div></section>
<section className="section video"><div className="container"><Media title="The Koffera Coffee Story"/></div></section>
<section className="cta"><div className="container"><div><span className="eyebrow light">Start a conversation</span><h2>Bring Ethiopian coffee to your market.</h2><p>Tell Koffera the origin, grade, process, quantity and destination you need.</p></div><Link className="btn cream" to="/contact">Request an offer <ArrowRight size={17}/></Link></div></section></main>}
function Coffees(){return <main><PageHero eyebrow="Our coffee" title="Ethiopian coffees with a clearer buyer story." text="Explore sample catalogue cards prepared for Koffera’s future verified origins, grades and availability."/><section className="section cream-bg"><div className="container"><div className="catalogue-note"><Coffee/><span>Sample catalogue — final product records are still required.</span></div><div className="coffee-grid catalogue">{[...coffees,{name:'Commercial Arabica',region:'Origin to confirm',process:'Commercial',tone:'dark',text:'Commercial-grade placeholder ready for final specification, screen size, moisture and packaging data.'}].map(c=><CoffeeCard key={c.name} coffee={c}/>)}</div></div></section></main>}
function PageHero({eyebrow,title,text}){return <section className="page-hero"><Beans/><div className="container"><span className="eyebrow light">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div></section>}
function About(){return <main><PageHero eyebrow="About Koffera" title="Rooted in Ethiopia. Designed for lasting coffee partnerships." text="A focused company story balancing heritage, leadership and commercial credibility."/><section className="section"><div className="container split"><Media portrait title="Company or founder image"/><div><Heading eyebrow="Our company" title="A concise story with stronger business relevance." text="Koffera is presented as an Ethiopian coffee-export brand serving international roasters, importers and distributors. The legal identity and export-licence details must be confirmed."/><p className="muted">The final page should explain sourcing, quality, supplier relationships and export support using verified facts and real photography.</p><Link className="btn dark" to="/contact">Contact Koffera <ArrowRight size={16}/></Link></div></div></section><section className="section cream-bg"><div className="container mission"><article><span>Vision</span><h2>Represent Ethiopian coffee with integrity in international markets.</h2><p>Final wording requires management approval.</p></article><article><span>Mission</span><h2>Connect buyers with quality Ethiopian coffee and dependable export support.</h2><p>Final wording must match actual operations.</p></article></div></section></main>}
function Contact(){return <main><PageHero eyebrow="Buyer enquiry" title="Tell Koffera what coffee you are looking for." text="Share your preferred origin, process, grade, quantity and destination."/><section className="section cream-bg"><div className="container contact"><aside><span className="eyebrow">Direct contact</span><h2>Let’s start with the right information.</h2><p>Current contact details should be verified before final launch.</p><a href={`mailto:${company.email}`}><Mail/><span><small>Email</small><strong>{company.email}</strong></span></a><a href={`tel:${company.phone.replace(/\s/g,'')}`}><Phone/><span><small>Phone</small><strong>{company.phone}</strong></span></a><div><MapPin/><span><small>Office</small><strong>{company.location}</strong></span></div></aside><form onSubmit={e=>e.preventDefault()}><span className="eyebrow">Request information</span><h2>Buyer enquiry form</h2><div className="form-grid"><label>Full name<input required placeholder="Your name"/></label><label>Company<input required placeholder="Company name"/></label><label>Business email<input required type="email" placeholder="name@company.com"/></label><label>Country<input required placeholder="Country"/></label><label>Buyer type<select defaultValue=""><option value="" disabled>Select buyer type</option><option>Roaster</option><option>Importer / distributor</option><option>Private label</option><option>Other</option></select></label><label>Inquiry type<select defaultValue=""><option value="" disabled>Select inquiry</option><option>Request current offer</option><option>Request samples</option><option>General enquiry</option></select></label><label className="full">Coffee or origin<input placeholder="Example: Guji natural"/></label><label>Estimated quantity<input placeholder="Bags, kg or containers"/></label><label>Destination<input placeholder="Country or port"/></label><label className="full">Message<textarea rows="6" required placeholder="Tell us the grade, process, packaging and timing."/></label><button className="btn dark full">Submit enquiry <ArrowRight size={16}/></button></div></form></div></section></main>}
function Legal({title}){return <main className="legal"><div className="container"><span className="eyebrow">Legal placeholder</span><h1>{title}</h1><p>This page requires professionally approved legal content before final public launch.</p><Link className="text-link" to="/">Return home <ArrowRight size={16}/></Link></div></main>}
function NotFound(){return <main className="not-found"><div><span>404</span><h1>Page not found</h1><Link className="btn dark" to="/">Return home</Link></div></main>}
export default function App(){return <><ScrollTop/><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/coffees" element={<Coffees/>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/><Route path="/privacy" element={<Legal title="Privacy Policy"/>}/><Route path="/terms" element={<Legal title="Terms & Conditions"/>}/><Route path="*" element={<NotFound/>}/></Routes><Footer/></>}
