import React from 'react';
import ReactDOM from 'react-dom/client';
import {HashRouter} from 'react-router-dom';
import App from './App';
import ErrorBoundary from './components/ErrorBoundary';
import './styles-base.css';
import './styles-home.css';
import './styles-page.css';
import './styles-expanded.css';
import './styles-responsive.css';
ReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><ErrorBoundary><HashRouter><App/></HashRouter></ErrorBoundary></React.StrictMode>);
